### ISSUE TITLE
k8s導入

### ISSUE THREAD

**Issue by shiron-dev** [halcyon-org/belifeline-infra#45]

**Comment by shiron-dev** [comment]
crioとkubeletがsystemd enableでもうまく起動しないかも

**Comment by shiron-dev** [comment]
crioがlxcで動かないのでcontinerdにする

**Comment by shiron-dev** [comment]
LXCやめてVMをTerraformとCloudinitでいい感じに注入

**Comment by shiron-dev** [comment]
terraformでcf tunnel下のホストにproxyする方法がなくて、tfでcloudinitのymlを置けないっぽいので供養
ansibleにします...ansible(pve)->tf(infra)->ansible(subaru)->tf(k8s)みたいになるのが嫌だったけど...しかたないかぁ
```tf
resource "local_file" "cloud_init_user_data_file" {
  for_each = local.pve_subaru
  content  = templatefile("${path.module}/cloudinit/subaru.yml.tftpl", { name = each.value.name })
  filename = "${path.module}/files/${each.value.name}.yml"
}

resource "null_resource" "cloud_init_config_files" {
  for_each = local.pve_subaru

  connection {
    type          = "ssh"
    user          = "ansible_user"
    host          = "192.168.30.101"
    private_key   = file("${path.module}/../private/cert/ssh/subaru.key")
    proxy_command = "cloudflared access ssh --hostname halcyon-srv.shiron.dev -o ProxyCommand=\"cloudflared access ssh --hostname %h\""
  }

  provisioner "file" {
    source      = local_file.cloud_init_user_data_file[each.value.name].filename
    destination = "/var/lib/vz/snippets/user_data_vm-${each.value.name}.yml"
  }
}
```
```yml
#cloud-config
hostname: ${name}
manage_etc_hosts: true
fqdn: ${name}
chpasswd:
  expire: False
users:
  - default
  - name: ansible_user
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
ssh_pwauth: true
ssh_authorized_keys:
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEtMsUY0MRNGCYCQ0PPm7XprDdTZgK6C6PyjhPVktTLZ"
package_upgrade: true
```
